spring.application.name=sari-system

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
app.base-url=http://localhost:8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.static-locations=file:./uploads/

server.port=${PORT:8080}