spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:27100/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=STAyYLdgToxKjboqaIjbVFxoNRqzeMZt

spring.jpa.hibernate.ddl-auto=update