spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

app.base-url=${APP_BASE_URL}

spring.jpa.hibernate.ddl-auto=update

libreoffice.path=/usr/bin/soffice