spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:27100/railway?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
libreoffice.path=/Applications/LibreOffice.app/Contents/MacOS/soffice

